### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by m-usmansaeed** [nut-tech/nut-sdk-ios#1]
xCode Version 12.5 (12E262)

<img width="566" alt="Screen Shot 2021-05-10 at 6 32 37 PM" src="https://user-images.githubusercontent.com/6871717/117667780-b1cf7d80-b1be-11eb-9078-694e351c23b6.png">

<img width="1088" alt="Screen Shot 2021-05-10 at 6 24 30 PM" src="https://user-images.githubusercontent.com/6871717/117667791-b431d780-b1be-11eb-935b-6d480bd0cbd6.png">

**Comment by nutspace** [comment]
Thanks for your feedback, we will deal with this issue asap.

**Comment by nutspace** [comment]
@m-usmansaeed  Please try the new version.
